name: Build the IG
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

    # Install ruby
    # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

    # Install Jekyll
    # https://jekyllrb.com/docs/installation/ubuntu/
      - name: "Install Jekyll"
        shell: bash
        run: |
          gem install jekyll bundler
          jekyll -v

    # Install node if SUSHI is needed
    # https://github.com/actions/setup-node
      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: "Install and run SUSHI"
        shell: bash
        run: |
          npm install -g fsh-sushi@2.7.0
          sushi --version
          sushi .

      - name: "Download the IG Publisher"
        shell: bash
        run: |
          mkdir ./input-cache
          curl -sS -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar
          chmod +x ./input-cache/publisher.jar

      - name: "Create IG"
        shell: bash
        run: |
          java -jar -Xms4096M -Xmx6144M -XX:NewRatio=1 -XX:-UseAdaptiveSizePolicy input-cache/publisher.jar ig.ini

      # Deploy IG
      - name: "Deploy to kind-lab.github.io"
        run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git config --global credential.helper cache
            git clone --depth 1 https://${{ secrets.GH_MIMIC_PROFILES_PAT }}@github.com/kind-lab/kind-lab.github.io website
            mv output website/mimic-fhir
            cd website
            git add mimic-fhir
            git commit -a -m "$(date): update mimic-fhir IG"
            git push